feat: charity
otherplane/wittypixels-contracts pull request #9
Opened 2023-02-22 18:19 UTC by guidiaz

2023-02-24 00:29 UTC, aesedepece commented on migrations/settings.js
> +            endTs:   1677866400 + 7 * 3600, // Fri, 3 March 2023 18:00 GMT-7
Let's run the game until the 4th, as the event finishes on the 5th!

2023-02-24 00:40 UTC, aesedepece requested changes

2023-02-24 00:40 UTC, aesedepece commented on migrations/settings.js
> +            startingPrice: "32000000000000000000", // 32.00 ETH
Let's be bold here. I see no reason to start lower than 100 ETH.

2023-02-24 00:40 UTC, aesedepece commented on migrations/settings.js
> +            deltaPrice:       "50000000000000000", //  0.05 ETH
If we go with a starting price of 100ETH, deltaPrice will need to be 0.15 so as to keep the auction runtime shorter than 1 month.

2023-02-24 01:23 UTC, aesedepece commented on migrations/settings.js
> +            endTs:   1677866400 + 7 * 3600, // Fri, 3 March 2023 18:00 GMT-7
So 24h more would be `1677952800 + 7 * 3600`

2023-03-03 23:45 UTC, Tommytrg approved these changes

2023-03-09 10:03 UTC, aesedepece approved these changes

2023-03-09 14:46 UTC, merged